export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGINUP_USER = 'LOGINUP_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const EMAIL_VERIFY = 'EMAIL_VERIFY'
export const LOGUOT_USER = 'LOGUOT_USER'
export const LOGGEDOUT_USER = 'LOGGEDOUT_USER'

export const SET_ALERT = 'SET_ALERT'
export const RESET_ALERT = 'RESET_ALERT'